name: Create and publish a Docker image

env:
  # TODO: keep investigating how to use input and its default value
  DOCKERIMAGETAG: latest
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dockerimagetag:
        # TODO: keep investigating how to use input and its default value
        default: latest
        description: Docker image tag
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image using default docker image tag
        uses: docker/build-push-action@v4
        with:
          build-args: |
            IMAGE=alpine
            VERSION=latest
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.DOCKERIMAGETAG }}
      # Below step only executed if action triggered manually
      - name: Build and push Docker image using input docker image tag
        if: ${{ inputs.dockerimagetag }}
        uses: docker/build-push-action@v4
        with:
          build-args: |
            IMAGE=alpine
            VERSION=latest
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ inputs.dockerimagetag }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - name: Build and push Docker image with unique tag
        uses: docker/build-push-action@v4
        with:
          build-args: |
            IMAGE=alpine
            VERSION=latest
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.date.outputs.date }}
